services:
  app:
    container_name: "backend"
    build: .

  web:
    image: "nginx:latest"
    container_name: "web"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
